language: php

services:
  - mysql

# Main PHP version matrix builds.
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

# Main environment variable matrix builds.
env:
  global:
    - GRUNT=no
    - PHPUNIT=1
    - WP_MULTISITE=0
  matrix:
    - WP_VERSION=latest
    - WP_VERSION=trunk
    - WP_VERSION=5.1.1
    - WP_VERSION=5.0.4
    - WP_VERSION=4.9.10
    - WP_VERSION=4.8.9
    - WP_VERSION=4.7.13

matrix:
  fast_finish: true
  global:
    - env: GRUNT=no
  exclude:
    # WP >= 5.0.4 unsupported with PHPUnit 7 (PHP 7.1-7.3). Tests fail from WP errors.
    - php: 7.3
      env: WP_VERSION=5.0.4
    - php: 7.3
      env: WP_VERSION=4.9.10
    - php: 7.3
      env: WP_VERSION=4.8.9
    - php: 7.3
      env: WP_VERSION=4.7.13
    - php: 7.2
      env: WP_VERSION=5.0.4
    - php: 7.2
      env: WP_VERSION=4.9.10
    - php: 7.2
      env: WP_VERSION=4.8.9
    - php: 7.2
      env: WP_VERSION=4.7.13
    - php: 7.1
      env: WP_VERSION=5.0.4
    - php: 7.1
      env: WP_VERSION=4.9.10
    - php: 7.1
      env: WP_VERSION=4.8.9
    - php: 7.1
      env: WP_VERSION=4.7.13
  include:
    - name: "Grunt Tasks"
      language: node_js
      node_js:
        - "8.11.3"
      env:
        GRUNT=yes
        PHPUNIT=0
    - name: "WP Multisite"
      env:
        WP_MULTISITE=1
        PHPUNIT=1
        PHPUNIT_VERSION=local
    - name: "PHP 5.5 Test (WP <= 5.1)"
      dist: trusty
      php: 5.5
      env:
        WP_VERSION=5.1
        PHPUNIT=1
    - name: "PHP 5.4 Test (WP <= 5.1)"
      dist: trusty
      php: 5.4
      env:
        WP_VERSION=5.1
        PHPUNIT=1
    - name: "PHP 5.3 Test (Not supported by PHPUnit)"
      dist: precise
      php: 5.3
    - name: "PHP 5.2 Test (Not supported by PHPUnit)"
      dist: precise
      php: 5.2
  allow_failures:
    - env: WP_MULTISITE=1 PHPUNIT=1 PHPUNIT_VERSION=local
    - php: 5.3
      dist: precise
    - php: 5.2
      dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  except:
  - "/^*-v[0-9]/"

before_install:
  # Set PHPUnit Version if PHPUnit is enabled.
  - if [[ "1" = "$PHPUNIT" && -z "$PHPUNIT_VERSION" || "0" = "$PHPUNIT_VERSION"  ]]; then
      PHPUNIT_VERSION=$(bash bin/get-phpunit-compat-version.sh $TRAVIS_PHP_VERSION);
    fi
  # if 0 (false value), then disable PHPUnit.
  - if [[ "0" = "$PHPUNIT_VERSION" ]]; then
      PHPUNIT=0;
    fi

install:
  # Setup PHPUnit.
  - if [[ "1" = "$PHPUNIT" && "false" != "$TRAVIS_PULL_REQUEST" ]]; then
      bash bin/install-phpunit.sh $PHPUNIT_VERSION $TRAVIS_PHP_VERSION;
    fi
  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      chmod +x bin/init-grunt.sh; . bin/init-grunt.sh;
    fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      grunt;
    fi
  # Run PHPUnit on PR.
  - if [[ "1" = $PHPUNIT && "false" != "$TRAVIS_PULL_REQUEST" ]]; then
      ./vendor/bin/phpunit;
    fi

after_failure:
- cat "logs/phpcs.log"
- cat "logs/jslogs.log"
