language: php

php:
  - 7.2

matrix:
  fast_finish: true
  global:
    - env: PHPUNIT=global GRUNT=no
  include:
#    - php: 7.2
#      env: PHPUNIT=local
#    - php: 7.1
#      env: PHPUNIT=local
#    - php: 7.0
#    - php: 5.6
#    - php: 5.5
#    - php: 5.4
#    - php: 5.3
#      dist: precise
#    - php: 5.2
#      dist: precise
#    - env: WP_VERSION=latest PHPUNIT=local
#    - env: WP_VERSION=4.6 PHPUNIT=local
#    - env: WP_MULTISITE=1
    - name: "Grunt Task"
      language: node_js
      node_js:
       - "node"
#       - "10"
#       - "8.11.3"
      env: GRUNT=yes
#  allow_failures:
#    - env: WP_MULTISITE=1
#    - php: 5.3
#      dist: precise
#    - php: 5.2
#      dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  except:
  - "/^*-v[0-9]/"

install:
  - if [[ $PHPUNIT = "local" ]]; then composer install; fi
  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then chmod +x bin/init-grunt.sh; . bin/init-grunt.sh; fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
#  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
#  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
#  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
#  - echo "TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
#  - echo "TRAVIS_PULL_REQUEST_SLUG=$TRAVIS_PULL_REQUEST_SLUG"
#  - echo "PR=$PR"
#  - echo "BRANCH=$BRANCH"
#  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT"
#  - echo "TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE"
#  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG"
#  - echo "HOME=$HOME"
#  - echo "TRAVIS_ALLOW_FAILURE=$TRAVIS_ALLOW_FAILURE"
  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then grunt; fi
  - if [[ $PHPUNIT = "local" ]]; then ./vendor/bin/phpunit; else phpunit; fi

after_failure:
- cat "logs/phpcs.log"
- cat "logs/jslogs.log"

after_success:
#  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then chmod +x bin/init-grunt.sh; . bin/push.sh; fi

#  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then git fetch $TRAVIS_PULL_REQUEST_SLUG; fi
#  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then git checkout $TRAVIS_PULL_REQUEST_SLUG $BRANCH; fi
#  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then git add --all; fi
#  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then git commit -m "Grunt Patch"; fi
#  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then git push; fi
