language: php

services:
  - mysql

matrix:
  fast_finish: true
  global:
    - env: PHPUNIT=global GRUNT=no
  include:
    - name: "PHP 7.2 Test"
      php: 7.2
      env: PHPUNIT=8
    - name: "PHP 7.1 Test"
      php: 7.1
      env: PHPUNIT=7
    - name: "PHP 7.0 Test"
      php: 7.0
      env: PHPUNIT=6
    - name: "PHP 5.6 Test"
      php: 5.6
      env: PHPUNIT=5
    - name: "PHP 5.5 Test (WP 5.2 dropped support)"
      dist: trusty
      php: 5.5
      env: WP_VERSION=5.1 PHPUNIT=4
    - name: "PHP 5.4 Test (WP 5.2 dropped support)"
      dist: trusty
      php: 5.4
      env: WP_VERSION=5.1 PHPUNIT=4
    - name: "PHP 5.3 Test"
      dist: precise
      php: 5.3
      env: PHPUNIT=4
    - name: "PHP 5.2 Test"
      dist: precise
      php: 5.2
      env: PHPUNIT=4
    - name: "Latest WP version"
      env: WP_VERSION=latest PHPUNIT=local
    - name: "Minimum WP version"
      env: WP_VERSION=4.7 PHPUNIT=local
    - name: "WP Multisite"
      env: WP_MULTISITE=1
    - name: "Grunt Tasks"
      language: node_js
      node_js:
       - "8.11.3"
      env: GRUNT=yes
  allow_failures:
    - env: WP_MULTISITE=1
    - php: 5.3
      dist: precise
    - php: 5.2
      dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  except:
  - "/^*-v[0-9]/"

install:
  - if [[ ! -z "$PHPUNIT"]]; then
      bash bin/install-phpunit.sh $PHPUNIT $TRAVIS_PHP_VERSION
    fi
#  - if [[ $PHPUNIT = "local" ]]; then
#      composer install;
#    fi
  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      chmod +x bin/init-grunt.sh; . bin/init-grunt.sh;
    fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  - if [[ $GRUNT = "yes" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then grunt; fi
  - if [[ $PHPUNIT = "local" ]]; then ./vendor/bin/phpunit; else phpunit; fi

after_failure:
- cat "logs/phpcs.log"
- cat "logs/jslogs.log"
